version: '3'
services:
  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      database_url: 'postgres:secret@tcp(db:5432)/db'
      listen_port: 8092
    ports:
      - '8092:8092'
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=meta
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
# Names our volume
volumes:
  pg_project: